version: '3.0'
services:
    zoo1:
        build: .
        restart: always
        tty: true
        hostname: zoo1
        ports:
            - 2181:2181
            - 2888
            - 3888
        entrypoint: /docker-entrypoint.sh
        environment:
            ZOO_MY_ID: 1
        networks: 
          - solr

    zoo2:
        build: .
        restart: always
        hostname: zoo2
        tty: true
        ports:
            - 2182:2181
            - 2888
            - 3888
        entrypoint: /docker-entrypoint.sh
        environment:
            ZOO_MY_ID: 2
        networks: 
          - solr

    zoo3:
        build: .
        restart: always
        hostname: zoo3
        tty: true
        ports:
            - 2183:2181
            - 2888
            - 3888
        entrypoint: /docker-entrypoint.sh
        environment:
            ZOO_MY_ID: 3
        networks: 
          - solr

    solr1:
        container_name: solr1
        image: solr:8
        ports:
          - "8981:8983"
        environment:
          - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
        networks:
          - solr
        depends_on:
          - zoo1
          - zoo2
          - zoo3

    solr2:
        image: solr:8
        container_name: solr2
        ports:
          - "8982:8983"
        environment:
          - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
        networks:
          - solr
        depends_on:
          - zoo1
          - zoo2
          - zoo3

    solr3:
        image: solr:8
        container_name: solr3
        environment:
          - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
        ports:
          - "8983:8983"
        networks:
          - solr
        depends_on:
          - zoo1
          - zoo2
          - zoo3
networks: 
  solr: