apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zk-pvc-1
  labels:
    app: zk
    node: zk-pvc-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zk-pvc-2
  labels:
    app: zk
    node: zk-pvc-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zk-pvc-3
  labels:
    app: zk
    node: zk-pvc-3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard