apiVersion: v1
kind: Service
metadata:
  labels:
    app: solr
  name: solr
spec:
  type: LoadBalancer
  ports:
  - name: "8983"
    port: 8983
    targetPort: 8983
  selector:
    app: solr
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: solr
  name: solr1
spec:
  ports:
  - name: "8983"
    port: 8983
    targetPort: 8983
  selector:
    service: solr1
    app: solr
    node: solr1
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: solr
  name: solr2
spec:
  ports:
  - name: "8983"
    port: 8983
    targetPort: 8983
  selector:
    service: solr2
    app: solr
    node: solr2
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: solr1
    app: solr
    node: solr1
  name: solr1
spec:
  replicas: 1
  selector:
    matchLabels:
      service: solr1
      app: solr
      node: solr1
  strategy: {}
  template:
    metadata:
      labels:
        service: solr1
        app: solr
        node: solr1
    spec:
      containers:
      - env:
        - name: ZK_HOST
          value: zoo1:2181,zoo2:2182,zoo3:2183
        image: solr:8
        name: solr1
        ports:
        - containerPort: 8983
        resources: {}
      hostname: solr1
      restartPolicy: Always
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: solr2
    app: solr
    node: solr2
  name: solr2
spec:
  replicas: 1
  selector:
    matchLabels:
      service: solr2
      app: solr
      node: solr2
  strategy: {}
  template:
    metadata:
      labels:
        service: solr2
        app: solr
        node: solr2
    spec:
      containers:
      - env:
        - name: ZK_HOST
          value: zoo1:2181,zoo2:2182,zoo3:2183
        image: solr:8
        name: solr2
        ports:
        - containerPort: 8983
        resources: {}
      hostname: solr2
      restartPolicy: Always
status: {}