apiVersion: v1
kind: Service
metadata:
  labels:
    app: solr
  name: solr
spec:
  type: LoadBalancer
  ports:
  - name: "8983"
    port: 8983
    targetPort: 8983
  selector:
    app: solr
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: solr
  name: solr1
spec:
  ports:
  - name: "8983"
    port: 8983
    targetPort: 8983
  selector:
    service: solr1
    app: solr
    node: solr1
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: solr
  name: solr2
spec:
  ports:
  - name: "8983"
    port: 8983
    targetPort: 8983
  selector:
    service: solr2
    app: solr
    node: solr2
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: solr1-ss
  labels:
    app: solr
    node: solr1
    service: solr1
spec:
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: solr
      node: solr1
      service: solr1
  serviceName: solr1
  template:
    metadata:
      labels:
        app: solr
        service: solr1
        node: solr1
    spec:
      containers:
        - name: solr1
          image: solr:8
          env:
          - name: ZK_HOST
            value: zoo1:2181,zoo2:2182,zoo3:2183
          ports:
            - containerPort: 8983
          volumeMounts:
            - mountPath: /var/solr/data
              name: vct-solr-1
  volumeClaimTemplates:
    - metadata:
        name: vct-solr-1
        labels:
          app: solr
          node: solr1
          service: solr1
      spec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: solr2-ss
  labels:
    app: solr
    node: solr2
    service: solr2
spec:
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: solr
      node: solr2
      service: solr2
  serviceName: solr2
  template:
    metadata:
      labels:
        app: solr
        service: solr2
        node: solr2
    spec:
      containers:
        - name: solr2
          image: solr:8
          env:
          - name: ZK_HOST
            value: zoo1:2181,zoo2:2182,zoo3:2183
          ports:
            - containerPort: 8983
          volumeMounts:
            - mountPath: /var/solr/data
              name: vct-solr-2
  volumeClaimTemplates:
    - metadata:
        name: vct-solr-2
        labels:
          app: solr
          node: solr2
          service: solr2
      spec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi