apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk-ss
  labels:
    app: zoo
spec:
  selector:
    matchLabels:
      app: zoo
  serviceName: zoo
  replicas: 3
  template:
    spec:
      containers:
        - name: zoo1
        - name: zoo2
        - name: zoo3
