apiVersion: v1
kind: Service
metadata:
  labels:
    service: zoo1
    app: zoo
    node: zoo1
  name: zoo1
spec:
  ports:
  - name: "2181"
    port: 2181
    targetPort: 2181
  - name: "2888"
    port: 2888
    targetPort: 2888
  - name: "3888"
    port: 3888
    targetPort: 3888
  selector:
    service: zoo1
    app: zoo
    node: zoo1
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: zoo2
    app: zoo
    node: zoo2
  name: zoo2
spec:
  ports:
  - name: "2181"
    port: 2182
    targetPort: 2181
  - name: "2888"
    port: 2888
    targetPort: 2888
  - name: "3888"
    port: 3888
    targetPort: 3888
  selector:
    service: zoo2
    app: zoo
    node: zoo2
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: zoo3
    app: zoo
    node: zoo3
  name: zoo3
spec:
  ports:
  - name: "2181"
    port: 2183
    targetPort: 2181
  - name: "2888"
    port: 2888
    targetPort: 2888
  - name: "3888"
    port: 3888
    targetPort: 3888
  selector:
    service: zoo3
    app: zoo
    node: zoo3
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk1-ss
  labels:
    app: zoo
    node: zoo1
    service: zoo1
spec:
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: zoo
      node: zoo1
      service: zoo1
  serviceName: zoo1
  template:
    metadata:
      labels:
        app: zoo
        service: zoo1
        node: zoo1
    spec:
      containers:
        - name: zoo1
          image: naveenm1786/zoo
          env:
          - name: ZOO_SERVERS
            value: "server.1=zk1-ss-0.zoo1.default.svc.cluster.local:2888:3888 server.2=zk2-ss-0.zoo2.default.svc.cluster.local:2888:3888 server.3=zk3-ss-0.zoo3.default.svc.cluster.local:2888:3888"
          - name: ZOO_MY_ID
            value: "1"
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
          volumeMounts:
            - mountPath: /data
              name: vct-zk-1
  volumeClaimTemplates:
    - metadata:
        name: vct-zk-1
        labels:
          app: zoo
          node: zoo1
          service: zoo1
      spec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk2-ss
  labels:
    app: zoo
    node: zoo2
    service: zoo2
spec:
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: zoo
      node: zoo2
      service: zoo2
  serviceName: zoo2
  template:
    metadata:
      labels:
        app: zoo
        service: zoo2
        node: zoo2
    spec:
      containers:
        - name: zoo2
          image: naveenm1786/zoo
          env:
          - name: ZOO_SERVERS
            value: "server.1=zk1-ss-0.zoo1.default.svc.cluster.local:2888:3888 server.2=zk2-ss-0.zoo2.default.svc.cluster.local:2888:3888 server.3=zk3-ss-0.zoo3.default.svc.cluster.local:2888:3888"
          - name: ZOO_MY_ID
            value: "2"
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
          volumeMounts:
            - mountPath: /data
              name: vct-zk-2
  volumeClaimTemplates:
    - metadata:
        name: vct-zk-2
        labels:
          app: zoo
          node: zoo2
          service: zoo2
      spec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk3-ss
  labels:
    app: zoo
    node: zoo3
    service: zoo3
spec:
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: zoo
      node: zoo3
      service: zoo3
  serviceName: zoo3
  template:
    metadata:
      labels:
        app: zoo
        service: zoo3
        node: zoo3
    spec:
      containers:
        - name: zoo3
          image: naveenm1786/zoo
          env:
          - name: ZOO_SERVERS
            value: "server.1=zk1-ss-0.zoo1.default.svc.cluster.local:2888:3888 server.2=zk2-ss-0.zoo2.default.svc.cluster.local:2888:3888 server.3=zk3-ss-0.zoo3.default.svc.cluster.local:2888:3888"
          - name: ZOO_MY_ID
            value: "3"
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
          volumeMounts:
            - mountPath: /data
              name: vct-zk-3
  volumeClaimTemplates:
    - metadata:
        name: vct-zk-3
        labels:
          app: zoo
          node: zoo3
          service: zoo3
      spec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

